- name: Copying cron config
  template:
    src: "cron-task.j2"
    dest: "~/shadowsocks_config/docker/certbot/cron-task.sh"


- name: Using base nginx config for certificate generation
  template:
    src: "nginx-certgen.j2"
    dest: "~/shadowsocks_config/docker/nginx/default.conf"


- name: Restarting nginx service
  docker_compose:
    project_src: "~/shadowsocks_config/docker"
    restarted: yes
    services: "nginx"
  register: output


- name: Running certbot container
  docker_compose:
    project_src: "~/shadowsocks_config/docker"
    build: yes
    services: certbot
  register: output
