- name: Copy cron config
  template:
    src: "cron-task.j2"
    dest: "~/nginx_conf/docker/certbot/cron-task.sh"

- name: Run certbot container and generate keys
  docker_compose:
    project_src: "~/nginx_conf/docker"
    build: yes
    services: certbot
  register: output

- name: Restart nginx container
  docker_compose:
    project_src: "~/nginx_conf/docker"
    restarted: yes
    services: "nginx"
  register: output