- name: Tear down existing nginx service
  docker_compose:
    project_src: "/home/{{ user }}/nginx_conf/docker"
    state: absent
    remove_images: local
    services: "nginx"

- name: Create and start nginx service
  docker_compose:
    project_src: "/home/{{ user }}/nginx_conf/docker"
    build: yes
    services: "nginx"
  register: output