- name: Setting nginx.conf file
  template:
    src: "nginx-release.j2"
    dest: "~/shadowsocks_config/docker/nginx/default.conf"


- name: Building nginx service
  docker_compose:
    project_src: "~/shadowsocks_config/docker"
    build: yes
    services: "nginx"
  register: output


- name: Restarting nginx service
  docker_compose:
    project_src: "~/shadowsocks_config/docker"
    restarted: yes
    services: "nginx"
  register: output