version: "3.3"
services:

# Nginx server
  nginx:
    restart: always
    container_name: nginx_container
    image: nginx
    network_mode: host
    volumes:
      - ~/shadowsocks_config/certs-data/letsencrypt/:/data/letsencrypt/:ro
      - ~/shadowsocks_config/certs-data/certs/:/data/certs/:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf/:rw


# Certificate generation
  certbot:
    container_name: certbot_container
    network_mode: host
    volumes:
      - ~/shadowsocks_config/certs-data/letsencrypt/:/data/letsencrypt/:rw
      - ~/shadowsocks_config/certs-data/certs/:/etc/letsencrypt/:rw
    build:
      context: .
      dockerfile: ./certbot/Dockerfile


# Shadowsocks server
  shadowsocks:
    container_name: shadowsocks_container
    image: teddysun/shadowsocks-rust
    network_mode: host
    restart: always
    volumes:
      - ./shadowsocks/config.json:/etc/shadowsocks-rust/config.json/:rw
      - ~/shadowsocks_config/certs-data/certs/:/data/certs/:rw
