version: "3.3"
services:

# Nginx server
  nginx:
    restart: always
    container_name: nginx_container
    image: nginx
    network_mode: host
    volumes:
      - letsencrypt:/data/letsencrypt/:ro
      - certs:/data/certs/:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf/:rw


# Certificate generation
  certbot:
    container_name: certbot_container
    restart: always
    network_mode: host
    volumes:
      - letsencrypt:/data/letsencrypt/:rw
      - certs:/etc/letsencrypt/:rw
    build:
      context: .
      dockerfile: ./certbot/Dockerfile


# Shadowsocks server
  shadowsocks:
    container_name: shadowsocks_container
    build:
      context: .
      dockerfile: ./shadowsocks/Dockerfile
    command: ["ss-server", "-c", "/etc/shadowsocks/config.json"]
    network_mode: host
    restart: always
    volumes:
      - ./shadowsocks/config.json:/etc/shadowsocks/config.json/:rw
      - certs:/data/certs/:rw

volumes:
  certs:
  letsencrypt:
    driver: local